services:

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./Docker/db-data/mysql-data:/var/lib/mysql
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "${ZIPKIN_PORT}:9411"